const { slowCypressDown } = require("cypress-slow-down")

describe('HIGEA', ()=>{
    slowCypressDown(400)
    
    beforeEach(()=>{
        cy.session('Iniciar sesion', ()=>{
            const email= 'drodriguez.itecnologica@gmail.com'
            const password='1'
            cy.login(email,password)
        })
    })

    it('Agendar consulta', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#new-appointment-ext').click()
        cy.get('#ambulatorio').select('6c733f6c-98b5-11e3-bc9a-00155d011f05') //metropolis
        cy.get('#especialidad').select('9993c360-34d8-11eb-a9a7-47f105db8ce2')
        cy.get('#medico').select('d13516ca-ac3c-11ec-a04c-8b3cfc441426')
        cy.get('#motivo').type('chequeo general')
        cy.get('#fecha').click()
        cy.get('#fecha').type('02/07/2024')
        cy.get('#appointment-ext-form').click()
        cy.get('#hora').select('a7e41c76-459c-11ee-96eb-0a2087879d15')
        cy.get('.mr-1').click()     
        cy.get('#btn-confirmar-cita-ext').click()
        cy.get('#swal2-html-container').should('contain','Tu cita ha sido programada')
        cy.wait(2000)
        cy.get('.swal2-confirm').click()
    })
 
    it('Agendar imagen', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#new-appointment-img').click()
        cy.wait(2000)
        cy.get('#ambulatorio_i').select('6c733f6c-98b5-11e3-bc9a-00155d011f05') //metropolis
        cy.get('#examen').type('RX DE COLUMNA CERVICAL DINAMICA')
        cy.get('#cita-attach-doc-orden').click()
        cy.get('[type="file"]').attachFile('../fixtures/orden.png')
        cy.get('#btn-copy-file-name-orden').click()
        cy.get('#fecha_img').type('02/07/2024')
        cy.get('.mr-1').click()
        cy.get('#btn-confirmar-cita-img').click()
        cy.get('.swal2-confirm').click()
        cy.get('#hora_img').select('07:30:00-07:38:00')
        cy.get('.mr-1').click()
        cy.get('#btn-confirmar-cita-img').click()
        cy.get('.swal2-popup').should('contain','Tu cita ha sido programada!')
        cy.wait(2000)
        cy.get('.swal2-confirm').click()
    })

    it('Ver recipe', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#recipes').click()
        //cy.wait(2000)
        cy.get('.glyphicon-print').click()
        cy.wait(2000)
    })

    it('Ver informe', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#patients-selector > select').select('bb673128-2ce8-11ef-bb4c-1276b73c6473')
        cy.get('#informes').click()
        //cy.wait(2000)
        cy.get('.glyphicon-print').click()
        cy.wait(2000)
    })

    it('Actualizar datos', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#datos').click()
        cy.wait(2000)
        cy.get('#patient-lugar')
        .clear()
        .type('Barquisimeto')
        cy.get('#patient-country').select('b80c8fef-a677-5340-85fb-2c162d75df03')
        cy.get('#patient-state').select('2342aa20-6cb6-53c8-9764-61bcac17bdcc')
        cy.get('#patient-city').select('9daf72ab-21fd-5c8c-82be-82aa3e2ee9a9')
        cy.get('#btn-submit-frm').click()
        cy.get('#swal2-html-container').should('contain','Los datos han sido almacenados con exito.')
        cy.wait(2000)
        cy.get('.swal2-confirm').click()
    })

    it('Eliminar consultas', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.wait(1000)
        cy.get('#citas').click()
        //cy.wait(2000)
        cy.get('#dynamic-subcontent > :nth-child(1)').click()
        cy.get('.glyphicon-trash').click()
        cy.get('.swal2-popup').should('contain','Cita Eliminada')
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
        cy.get('#appointment-img').click()
        cy.get('.glyphicon-trash').click()
        cy.get('.swal2-popup').should('contain','Cita Eliminada')
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
    })

  it('Nuevo afiliado, menor de edad', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('No')
        cy.wait(2000)
        cy.get('#patient-firstname-new').type('Daniel')
        cy.get('#patient-firstname-s-new').type('Josue')
        cy.get('#patient-lastname-new').type('Rodriguez')
        cy.get('#patient-lastname-s-new').type('Aguero')
        cy.get('#patient-birthday-new').type('29/09/2015')
        cy.get('#patient-sex-new').select('M')
        cy.get('#patient-phonenumber-new').type('04245452494')
        cy.get('#patient-type-new').select('42120e06-3d0b-11e4-b928-00155d011f05')
        cy.get('#patient-lugar-new').type('Barquisimeto')
        cy.get('#patient-country-new').select('b80c8fef-a677-5340-85fb-2c162d75df03')
        cy.get('#patient-state-new').select('2342aa20-6cb6-53c8-9764-61bcac17bdcc')
        cy.get('#patient-city-new').select('9daf72ab-21fd-5c8c-82be-82aa3e2ee9a9')
        cy.get('#patient-address-new').type('Barrio Union, Carrera 2 con calles 5 y 6')

        cy.get('#representative-firstname-new').type('Willianna')
        cy.get('#representative-firstname-s-new').type('Graciela')
        cy.get('#representative-lastname-new').type('Aguero')
        cy.get('#representative-lastname-s-new').type('Alejos')
        cy.get('#representative-iddoc-type-new').select('V')
        cy.get('#representative-iddoc-new').type('15444921')
        cy.get('#representative-sex-new').select('F')
        cy.get('#representative-birthday-new').type('02/05/1982')
        cy.get('#representative-afinity-new').select('b80c8fef-a677-5340-85fb-2c162d75df03')
        cy.get('#representative-email-new').type('testest@gmail.com')
        cy.get('#representative-phonenumber-new').type('04245452494')
        cy.get('#btn-submit-frm-new').click()
        cy.get('.swal2-popup').should('contain', 'Paciente registrado existosamente!')
        cy.wait(2000)
    }) 

    it('Nuevo afiliado', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('Si')
        cy.get('#patient-iddoc-type-new').select('V')
        cy.get('#patient-iddoc-new').type('13922398')
        cy.get('#patient-data-form-new > :nth-child(4)').click()
        cy.get('#patient-firstname-new').type('Daniel')
        cy.get('#patient-lastname-new').type('Rodriguez')
        cy.get('#patient-birthday-new').type('04/02/1979')
        cy.get('#patient-sex-new').select('Masculino')
        cy.get('#patient-type-new').select('42120e06-3d0b-11e4-b928-00155d011f05')
        cy.get('#patient-lugar-new').type('Baruisimeto')
        cy.get('#patient-phonenumber-new').type('04245859345')
        cy.get('#patient-address-new').type('Carrera 2 con 5 y 6 B.U')
        cy.get('#btn-submit-frm-new').click()
        cy.wait(2000)

    }) 

    it('Nuevo afiliado, Usuario ya existe', ()=>{
        cy.visit('https://qa-portalpaciente.centrodiagnosticohigea.com/portal_paciente/home.html')
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('Si')
        cy.get('#patient-iddoc-type-new').select('V')
        cy.get('#patient-iddoc-new').type('3324874')
        cy.get('#patient-data-form-new > :nth-child(4)').click()
        cy.get('.swal2-popup').should('contain', 'Existe un paciente con esta cédula, se cargaran los datos del registro para afiliar el paciente.')
        cy.get('.swal2-confirm').click()
        cy.get('#btn-submit-frm-new').click()  
        cy.wait(2000)
    })
        
})