describe('HIGEA', ()=>{
    beforeEach(()=>{
        const email='drodriguez.itecnologica@gmail.com'
        const password='1'
        cy.login(email,password)
    })
/*    it('Nuevo afiliado, menor de edad', ()=>{
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('No')
        cy.wait(2000)
        cy.get('#patient-firstname-new').type('Daniel')
        cy.get('#patient-firstname-s-new').type('Josue')
        cy.get('#patient-lastname-new').type('Rodriguez')
        cy.get('#patient-lastname-s-new').type('Aguero')
        cy.get('#patient-birthday-new').type('29/09/2015')
        cy.get('#patient-sex-new').select('M')
        cy.get('#patient-phonenumber-new').type('04245452494')
        cy.get('#patient-type-new').select('42120e06-3d0b-11e4-b928-00155d011f05')
        cy.get('#patient-lugar-new').type('Barquisimeto')
        cy.get('#patient-country-new').select('b80c8fef-a677-5340-85fb-2c162d75df03')
        cy.get('#patient-state-new').select('2342aa20-6cb6-53c8-9764-61bcac17bdcc')
        cy.get('#patient-city-new').select('9daf72ab-21fd-5c8c-82be-82aa3e2ee9a9')
        cy.get('#patient-address-new').type('Barrio Union, Carrera 2 con calles 5 y 6')
        //cy.get('#btn-submit-frm-new').click()

        cy.get('#representative-firstname-new').type('Willianna')
        cy.get('#representative-firstname-s-new').type('Graciela')
        cy.get('#representative-lastname-new').type('Aguero')
        cy.get('#representative-lastname-s-new').type('Alejos')
        cy.get('#representative-iddoc-type-new').select('V')
        cy.get('#representative-iddoc-new').type('15444921')
        cy.get('#representative-sex-new').select('F')
        cy.get('#representative-birthday-new').type('02/05/1982')
        cy.get('#representative-afinity-new').select('b80c8fef-a677-5340-85fb-2c162d75df03')
        cy.get('#representative-email-new').type('testest@gmail.com')
        cy.get('#representative-phonenumber-new').type('04245452494')
        cy.get('#btn-submit-frm-new').click()
        cy.get('.swal2-popup').should('contain', 'Paciente registrado existosamente!')
        cy.wait(2000)
    }) 

    it('Nuevo afiliado', ()=>{
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('Si')
        cy.get('#patient-iddoc-type-new').select('V')
        cy.get('#patient-iddoc-new').type('13922398')
        cy.get('#patient-data-form-new > :nth-child(4)').click()
        cy.get('#patient-firstname-new').type('Daniel')
        cy.get('#patient-lastname-new').type('Rodriguez')
        cy.get('#patient-birthday-new').type('04/02/1979')
        cy.get('#patient-sex-new').select('Masculino')
        cy.get('#patient-type-new').select('42120e06-3d0b-11e4-b928-00155d011f05')
        cy.get('#patient-lugar-new').type('Baruisimeto')
        cy.get('#patient-phonenumber-new').type('04245859345')
        cy.get('#patient-address-new').type('Carrera 2 con 5 y 6 B.U')
        cy.get('#btn-submit-frm-new').click()
        cy.wait(2000)

    }) 

    it('Nuevo afiliado, Usuario ya existe', ()=>{
        cy.get('#pacientes').click()
        cy.get('#btn-new-patient').click()
        cy.get('#patient-cedula-si-new').select('Si')
        cy.get('#patient-iddoc-type-new').select('V')
        cy.get('#patient-iddoc-new').type('3324874')
        cy.get('#patient-data-form-new > :nth-child(4)').click()
        cy.get('.swal2-popup').should('contain', 'Existe un paciente con esta cédula, se cargaran los datos del registro para afiliar el paciente.')
        cy.get('.swal2-confirm').click()
        cy.get('#btn-submit-frm-new').click()  
        cy.wait(2000)
    })
        */
})